### ISSUE TITLE
Add reserve fuel in surface dict

### ISSUE THREAD

**Issue by shamsheersc19** [mdolab/OpenAeroStruct#153]
Instead of adding the reserve fuel weight to the W0 indep var comp output, add it to the surface dict (like in tests/test_wingbox_fuel_vol_constraint_opt.py) and then consistently add it to W0 in the rest of the code. Or something along these lines.

**Comment by johnjasa** [comment]
@shamsheersc19 where do we sit on this?

**Comment by johnjasa** [comment]
Now this issue is to clearly say what W0 is and what it is:
W0 = OEW - structural_weight - fuelburn + reserve_fuel + payload

The structural_weight will be computed by weights.py
fuelburn by breguet range or IDVP
reserve fuel is set in surface dict
payload is set by user in W0

Need to add docs for this and introduce this to all relevant test files; don't hardcode in the W0, call it from the dict

**Comment by shamsheersc19** [comment]
This was addressed in the wingbox walkthrough and updated examples.
