### ISSUE TITLE
Visualization of the lifting surface

### ISSUE THREAD

**Issue by JotaHG** [mdolab/OpenAeroStruct#263]
I am trying to visulize the wing of the tutorial Aerodynamic Optimization Walkthrough but when I use `plot_wing aero.db` my terminal says 

>   File "<ipython-input-8-9f3272237371>", line 1
    plot_wing aero.db
.                       ^
SyntaxError: invalid syntax

How do I fix this error?

thanksss

**Comment by johnjasa** [comment]
Are you running this in your command terminal, such as bash or Windows cmd prompt? It looks like your command was run through a Python interpreter instead of entered at a normal terminal.

To be clear, wherever you actually run your case by typing something like `python run_case.py` is where you want to do `plot_wing aero.db`.

Let me know if this doesn't address your problem.

**Comment by JotaHG** [comment]
I didn't express myself correctly. Actually I tried this on Jupyter and Spyder, both softwares that comes in the Anaconda package for Windows 10 and none of them worked.

**Comment by johnjasa** [comment]
Both Jupyter and Spyder are IDEs for running Python code, and they usually allow you to run the code that's currently being edited in the IDE. However, you want to open up a console terminal to use the `plot_wing` utility.

Specifically, the Anaconda prompt on Windows is where you want to issue the command. So you can open an Anaconda prompt instance, navigate to the folder where the .db file is, then do `plot_wing aero.db`.

Alternatively, instead of doing what I suggested there, you can manually modify the `plot_wing` code and hardcode the .db name you want to look at, then run that code. Specifically, you would change line 49 (https://github.com/mdolab/OpenAeroStruct/blob/master/openaerostruct/utils/plot_wing.py#L49) to something like `self.db_name = aero.db`, then run the `plot_wing` file from your IDE. Make sure the `aero.db` file is in the same directory as the `plot_wing.py` in that case.

**Comment by JotaHG** [comment]
I did what you said using the Anaconda prompt. I navigated to the folder where the .db file is, then did `plot_wing aero.db`, but this time the prompt indicated an error:

> TypeError: __ init __() got an unexpected keyword argument 'pre_load'

**Comment by johnjasa** [comment]
Try updating to the latest version of OpenMDAO via the master branch of their GitHub: https://github.com/OpenMDAO/openmdao and then give it another try, that `pre_load` keyword was recently introduced.

**Comment by JotaHG** [comment]
Now it is working fine. Thank you so much for the help and patience.

**Comment by johnjasa** [comment]
Great! Glad to get it figured out. Don't hesitate to post if anything else isn't working for you.

**Comment by zachback64** [comment]
This thread helped me understand the issue I was facing with plotting the results of the optimization in the [Aerodynamic Optimization Walkthrough](https://mdolab-openaerostruct.readthedocs-hosted.com/en/latest/aero_walkthrough.html)

The first problem was that I was entering the plot_wing command in the python environment, rather than in terminal. It would help if, in the walkthrough, this instruction was made explicit. The command does appear in a different text format, though as a new user I did not interpret this as a command that should be sent outside of the python environment.

The second problem is that the saved file is named "aero_analysis_test.db" while the walkthrough instructs the user to input "plot_wing aero.db" . The correct file name needs to be used to view the plot.

Perhaps it would be useful to update the walkthrough instructions.
