### ISSUE TITLE
Negative fuel burn

### ISSUE THREAD

**Issue by btracey** [mdolab/OpenAeroStruct#32]
Cloning from master branch, and adding the following conditions (before the call to `OAS_prob.run()`:

```
OAS_prob.prob['alpha'] = -5.4772415561327445
OAS_prob.prob['wing.thickness_cp'] = np.array([ 0.14340327207903325, 0.3639890838470242, 0.2653579033716302])
OAS_prob.prob['wing.twist_cp'] = np.array([ -8.541536161392285, 5.030094299899314, -4.063335448175808])
```

This returns a solution with 
```
Fuelburn: -74795.1319562
wing_perf.failure -0.315245694701
wing_perf.thickness_intersects [-0.08346824 -0.28824473]
```

That is, the thickness doesn't intersect, the wing doesn't fail, but the fuelburn is negative.

**Comment by johnjasa** [comment]
For this design point, there's a negative amount of lift generated. The Breguet fuel burn equation is not valid when there's a negative lift. That is because the equation is fuelburn = np.sum((W0 + Ws) * (np.exp(R * CT / a / M * CD / CL) - 1)), and when CL is negative, this quantity evaluates to a negative value. You can think of it as the aircraft not needing to burn fuel to descend.

We usually avoid this possible issue by imposing a constraint that the lift generated must equal the weight of the aircraft so it can sustain level flight. This is `L_equals_W` within OpenAeroStruct. You could also impose a CL constraint to ensure that the CL is positive, at least. Another option is to postprocess the fuel burn so instead of a negative number it's a very large number so the optimizer doesn't prefer that design.
