### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by nwu63** [mdolab/OpenAeroStruct#346]
# Description
While the rest of MDO Lab tools are moving over to Azure Pipelines, OAS has several unique features that make GitHub Actions more appropriate
- no need to rely on MDO Lab-built Docker images
- completely open source
- need to deploy to GitHub Pages

Because of this, we should try to move this repo away from Travis to GH Actions as soon as possible.

**Comment by bernardopacini** [comment]
I can support this effort as I have experience with Github Actions now as well.

**Comment by kanekosh** [comment]
Will work on this later next week, and thanks @bernardopacini !

**Comment by kanekosh** [comment]
I am working on the migration (on my branch) and I have a few questions. I was just wondering if you already went through these and know a quick solution. Otherwise I will spend some time by myself, so please don't be bothered.

- We need an alternative to `travis-sphinx` to deploy the docs on the github. Do you know what we can use? 
- OAS has a few tests which require pySpline, which requires OpenMPI and gfortran. I could write a few lines to install them, but it might be time-consuming to do so every time. I believe we skipped these installations on Travis via `addons`, am I correct? Do you know a similar way to avoid the installations on Github Actions?

**Comment by nwu63** [comment]
>   * We need an alternative to `travis-sphinx` to deploy the docs on the github. Do you know what we can use?

I have no idea, but I'm sure publishing Sphinx docs to GitHub Pages is possible and fairly standard for GitHub Actions.


>   * OAS has a few tests which require pySpline, which requires OpenMPI and gfortran. I could write a few lines to install them, but it might be time-consuming to do so every time. I believe we skipped these installations on Travis via `addons`, am I correct? Do you know a similar way to avoid the installations on Github Actions?

Exactly, that will run `apt-get install` and install the pre-built packages on Ubuntu. Azure does not have the same convenience, but you can simply run `sudo apt install <dependency>` manually. Looking at [this](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md), gfortran should be already installed but the others have to be manually included in the build steps.

**Comment by bernardopacini** [comment]
I do not have experience with building and publishing Sphinx documentation on Github, but I believe the following extension may be useful: https://github.com/marketplace/actions/sphinx-build. We should be able to use actions to build the docs before publishing if need be, but the referenced extension may simplify everything without needing actions.

For pySpline and dependencies, I agree with what Neil said. While slow, it should just be one or two lines in the yaml file to setup the environment.

**Comment by kanekosh** [comment]
Thanks guys, I'll be working on the docs build. I added the dependencies installation, and it actually didn't take that long.
